arena_camera/usb_cam:
  ros__parameters:
    # find out available settings for different cam with v4l2-ctl --device=/dev/video6 --list-ctrls
    
    # Hardware
    #video device to be set as launch argument or environment variable ARENA_CAMERA_DEVICE
    video_device: "/dev/video4"                         # video device, can be overridden via launch argument
    camera_name: "GlobalShutterCamera_GlobalS___SB__PCI0_XHC__RHUB_HS03_3_1_0_32e4_0144_800x600"                        # string: camera name
    camera_info_url: "package://arena_perception/config/arena_camera_info_fs_960.yaml"                              # string: calibration file
    frame_id: "arena_camera_optical"                     # string: TF frame
    
    #Image format  
    image_width: 1280                                   # int: resolution width  #800 is best
    image_height: 960                                  # int: resolution heigh  #600 is best
    framerate: 60.0                                   # float: target FPS
    pixel_format: "mjpeg2rgb"                               # string: 'yuyv', 'mjpeg', 'grey' -> 'yuyv' often also used in greyscale cams