# config/opponent_det_pipeline_config.yaml

opponent_det_ColorSingle:
  ros__parameters:
    camera_frame: "arena_camera_optical"
    input_topic: "/arena_camera/image_rect_masked"
    topic_2d: "/detections_2d/color"
    topic_viz: "/debug/color_point"
    enabled: true
    min_contour_area: 200
    max_contour_area: 8000
    hue_min: 0
    hue_max: 179
    sat_min: 50
    sat_max: 255
    val_min: 50
    val_max: 255
    ignore_radius_px: 100
    shadow_expansion_factor: 1.2
    interactive_selection: true
    selection_window_name: "Color Selector - Click on opponent"
    stationary_timeout: 2.0
    debug: true

opponent_det_MOG2single:
  ros__parameters:
    camera_frame: "arena_camera_optical"
    input_topic: "/arena_camera/image_rect_masked"
    topic_2d: "/detections_2d/mog2"
    topic_viz: "/debug/mog2_point"
    enabled: true
    min_contour_area: 300
    max_contour_area: 10000
    background_history: 500
    var_threshold: 16
    ignore_radius_px: 100
    shadow_expansion_factor: 1.2
    stationary_timeout: 2.0
    debug: true

detection_2d_to_3d_color:
  ros__parameters:
    target_frame: "world"
    camera_frame: "arena_camera_optical"
    z_plane: 0.0
    confidence_threshold: 0.5
    tf_timeout_sec: 0.1
    publish_visualization: true

detection_2d_to_3d_mog2:
  ros__parameters:
    target_frame: "world"
    camera_frame: "arena_camera_optical"
    z_plane: 0.0
    confidence_threshold: 0.5
    tf_timeout_sec: 0.1
    publish_visualization: true

detection_kalman_filter:
  ros__parameters:
    target_frame: "world"
    opponent_frame: "opponent"
    update_rate: 20.0
    input_topics: ["/detections_3d/color_array", "/detections_3d/mog2_array"] # "/detections_3d/color_array", 
    measurement_noises: [0.08, 0.04]
    process_noise_position: 0.05
    process_noise_velocity: 0.5
    initial_covariance_position: 0.2
    initial_covariance_velocity: 50.0
    max_gate_distance: 1.5
    max_missed_detections: 15
    vel_threshold_low: 0.008
    vel_threshold_high: 0.05
    smoothing_factor: 0.6
    min_confidence_to_update: 0.05
    default_orientation: [0.0, 0.0, 0.0, 1.0]